import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'Hindi (हिन्दी)' },
  { code: 'gu', label: 'Gujarati (ગુજરાતી)' },
  { code: 'ta', label: 'Tamil (தமிழ்)' },
  { code: 'bn', label: 'Bengali (বাংলা)' },
  { code: 'or', label: 'Odia (ଓଡ଼ିଆ)' },
  { code: 'te', label: 'Telugu (తెలుగు)' },
] as const;

export type LanguageCode = (typeof SUPPORTED_LANGUAGES)[number]['code'];
type TranslationKey = keyof typeof translations.en;
const PRODUCT_NAME = 'CYCLONE SIGHT AI';

const translations = {
  en: {
    dashboard: 'Dashboard', liveMonitoring: 'Live Monitoring', cycloneTracker: 'Cyclone Tracker', rapidIntensification: 'Rapid Intensification', forecastModels: 'Forecast & Models', impactRiskMap: 'Impact & Risk Map', alertsNotifications: 'Alerts & Notifications', historicalCyclones: 'Historical Cyclones', analyticsReports: 'Analytics & Reports', aiCopilot: 'AI Copilot', accountDatabase: 'Account & Database', settings: 'Settings', feedback: 'Feedback', navigation: 'Navigation', new: 'New', systemStatus: 'System Status', allSystemsOperational: 'All Systems Operational', dataSourcesOnline: 'Data Sources Online', viewDataSources: 'View Data Sources', search: 'Search cyclone, location, ID...', clear: 'Clear', install: 'Install', installed: 'PWA Installed', language: 'Language', preferredLanguage: 'Preferred Display Language', savePreferences: 'Save Preferences', preferencesSaved: 'Preferences Saved!', languageHelp: 'Choose the language used across the CycloneAI interface and AI Copilot responses.', units: 'Meteorological Units', windUnit: 'Wind Velocity Unit', pressureUnit: 'Atmospheric Pressure Unit', feedCache: 'MOSDAC Feed & Cache', syncFrequency: 'MOSDAC Telemetry Sync Frequency', channel: 'Default Satellite Spectral Channel', dataCache: 'Data Integrity & Cache Reset', clearCache: 'Clear Browser Cache', chat: 'CycloneAI Chat', conversationActive: 'Conversation active', publicGuidance: 'Public guidance', responseCoordination: 'Response coordination', coastalOperations: 'Coastal operations', forecastAnalysis: 'Forecast analysis', researchAnalysis: 'Research analysis', askCopilot: 'Ask about weather, alerts, or safety…', syncing: 'Syncing MOSDAC...', sync: 'Sync MOSDAC', archiveYear: 'Archive Year:', cyclone: 'Cyclone:', feedsActive: 'SCORPIO Feeds Active', status: 'Status:',
  },
  hi: { dashboard: 'डैशबोर्ड', liveMonitoring: 'लाइव निगरानी', cycloneTracker: 'चक्रवात ट्रैकर', rapidIntensification: 'तीव्र तीव्रीकरण', forecastModels: 'पूर्वानुमान और मॉडल', impactRiskMap: 'प्रभाव और जोखिम मानचित्र', alertsNotifications: 'अलर्ट और सूचनाएँ', historicalCyclones: 'ऐतिहासिक चक्रवात', analyticsReports: 'विश्लेषण और रिपोर्ट', aiCopilot: 'एआई सहायक', accountDatabase: 'खाता और डेटाबेस', settings: 'सेटिंग्स', feedback: 'प्रतिक्रिया', navigation: 'नेविगेशन', new: 'नया', systemStatus: 'सिस्टम स्थिति', allSystemsOperational: 'सभी सिस्टम कार्यरत हैं', dataSourcesOnline: 'डेटा स्रोत ऑनलाइन', viewDataSources: 'डेटा स्रोत देखें', search: 'चक्रवात, स्थान, आईडी खोजें...', clear: 'साफ़ करें', install: 'इंस्टॉल करें', installed: 'PWA इंस्टॉल है', language: 'भाषा', preferredLanguage: 'पसंदीदा प्रदर्शन भाषा', savePreferences: 'पसंद सहेजें', preferencesSaved: 'पसंद सहेजी गई!', languageHelp: 'CycloneAI इंटरफ़ेस और एआई सहायक के लिए भाषा चुनें।', units: 'मौसम विज्ञान इकाइयाँ', windUnit: 'हवा की गति की इकाई', pressureUnit: 'वायुमंडलीय दबाव इकाई', feedCache: 'MOSDAC फ़ीड और कैश', syncFrequency: 'MOSDAC टेलीमेट्री सिंक आवृत्ति', channel: 'डिफ़ॉल्ट सैटेलाइट चैनल', dataCache: 'डेटा अखंडता और कैश रीसेट', clearCache: 'ब्राउज़र कैश साफ़ करें', chat: 'CycloneAI चैट', conversationActive: 'बातचीत सक्रिय', publicGuidance: 'सार्वजनिक मार्गदर्शन', responseCoordination: 'प्रतिक्रिया समन्वय', coastalOperations: 'तटीय संचालन', forecastAnalysis: 'पूर्वानुमान विश्लेषण', researchAnalysis: 'अनुसंधान विश्लेषण', askCopilot: 'मौसम, अलर्ट या सुरक्षा के बारे में पूछें…', syncing: 'MOSDAC सिंक हो रहा है...', sync: 'MOSDAC सिंक करें', archiveYear: 'संग्रह वर्ष:', cyclone: 'चक्रवात:', feedsActive: 'SCORPIO फ़ीड सक्रिय', status: 'स्थिति:' },
  gu: { dashboard: 'ડેશબોર્ડ', liveMonitoring: 'લાઇવ મોનિટરિંગ', cycloneTracker: 'ચક્રવાત ટ્રેકર', rapidIntensification: 'ઝડપી તીવ્રીકરણ', forecastModels: 'આગાહી અને મોડલ', impactRiskMap: 'અસર અને જોખમ નકશો', alertsNotifications: 'ચેતવણીઓ અને સૂચનાઓ', historicalCyclones: 'ઐતિહાસિક ચક્રવાતો', analyticsReports: 'વિશ્લેષણ અને અહેવાલો', aiCopilot: 'AI સહાયક', accountDatabase: 'એકાઉન્ટ અને ડેટાબેઝ', settings: 'સેટિંગ્સ', feedback: 'પ્રતિસાદ', navigation: 'નેવિગેશન', new: 'નવું', systemStatus: 'સિસ્ટમ સ્થિતિ', allSystemsOperational: 'બધી સિસ્ટમ કાર્યરત છે', dataSourcesOnline: 'ડેટા સ્ત્રોતો ઓનલાઈન', viewDataSources: 'ડેટા સ્ત્રોતો જુઓ', search: 'ચક્રવાત, સ્થાન, ID શોધો...', clear: 'સાફ કરો', install: 'ઇન્સ્ટોલ કરો', installed: 'PWA ઇન્સ્ટોલ કરેલ', language: 'ભાષા', preferredLanguage: 'પસંદગીની પ્રદર્શન ભાષા', savePreferences: 'પસંદગીઓ સાચવો', preferencesSaved: 'પસંદગીઓ સાચવવામાં આવી!', languageHelp: 'CycloneAI ઇન્ટરફેસ અને AI સહાયક માટે ભાષા પસંદ કરો.', units: 'હવામાન એકમો', windUnit: 'પવન વેગ એકમ', pressureUnit: 'વાતાવરણીય દબાણ એકમ', feedCache: 'MOSDAC ફીડ અને કૅશ', syncFrequency: 'MOSDAC ટેલિમેટ્રી સિંક આવર્તન', channel: 'ડિફૉલ્ટ સેટેલાઇટ ચેનલ', dataCache: 'ડેટા અખંડિતતા અને કૅશ રીસેટ', clearCache: 'બ્રાઉઝર કૅશ સાફ કરો', chat: 'CycloneAI ચેટ', conversationActive: 'વાર્તાલાપ સક્રિય', publicGuidance: 'જાહેર માર્ગદર્શન', responseCoordination: 'પ્રતિસાદ સંકલન', coastalOperations: 'દરિયાકાંઠાની કામગીરી', forecastAnalysis: 'આગાહી વિશ્લેષણ', researchAnalysis: 'સંશોધન વિશ્લેષણ', askCopilot: 'હવામાન, ચેતવણી અથવા સલામતી વિશે પૂછો…', syncing: 'MOSDAC સિંક થઈ રહ્યું છે...', sync: 'MOSDAC સિંક કરો', archiveYear: 'આર્કાઇવ વર્ષ:', cyclone: 'ચક્રવાત:', feedsActive: 'SCORPIO ફીડ સક્રિય', status: 'સ્થિતિ:' },
  ta: { dashboard: 'டாஷ்போர்டு', liveMonitoring: 'நேரடி கண்காணிப்பு', cycloneTracker: 'புயல் கண்காணிப்பான்', rapidIntensification: 'விரைவான தீவிரமடைதல்', forecastModels: 'முன்னறிவிப்பு மற்றும் மாதிரிகள்', impactRiskMap: 'தாக்கம் மற்றும் ஆபத்து வரைபடம்', alertsNotifications: 'எச்சரிக்கைகள் மற்றும் அறிவிப்புகள்', historicalCyclones: 'வரலாற்றுப் புயல்கள்', analyticsReports: 'பகுப்பாய்வு மற்றும் அறிக்கைகள்', aiCopilot: 'AI உதவியாளர்', accountDatabase: 'கணக்கு மற்றும் தரவுத்தளம்', settings: 'அமைப்புகள்', feedback: 'கருத்து', navigation: 'வழிசெலுத்தல்', new: 'புதியது', systemStatus: 'அமைப்பு நிலை', allSystemsOperational: 'அனைத்து அமைப்புகளும் செயல்படுகின்றன', dataSourcesOnline: 'தரவு மூலங்கள் ஆன்லைனில்', viewDataSources: 'தரவு மூலங்களைக் காண்க', search: 'புயல், இடம், ID தேடுங்கள்...', clear: 'அழி', install: 'நிறுவு', installed: 'PWA நிறுவப்பட்டது', language: 'மொழி', preferredLanguage: 'விருப்பக் காட்சி மொழி', savePreferences: 'விருப்பங்களைச் சேமி', preferencesSaved: 'விருப்பங்கள் சேமிக்கப்பட்டன!', languageHelp: 'CycloneAI இடைமுகம் மற்றும் AI உதவியாளருக்கான மொழியைத் தேர்ந்தெடுக்கவும்.', units: 'வானிலை அலகுகள்', windUnit: 'காற்று வேக அலகு', pressureUnit: 'வளிமண்டல அழுத்த அலகு', feedCache: 'MOSDAC ஊட்டம் மற்றும் கேச்', syncFrequency: 'MOSDAC தொலைஅளவீட்டு ஒத்திசைவு இடைவெளி', channel: 'இயல்புநிலை செயற்கைக்கோள் சேனல்', dataCache: 'தரவு ஒருமைப்பாடு மற்றும் கேச் மீட்டமைப்பு', clearCache: 'உலாவி கேச்சை அழி', chat: 'CycloneAI அரட்டை', conversationActive: 'உரையாடல் செயலில்', publicGuidance: 'பொது வழிகாட்டல்', responseCoordination: 'பதில் ஒருங்கிணைப்பு', coastalOperations: 'கடலோர செயல்பாடுகள்', forecastAnalysis: 'முன்னறிவிப்பு பகுப்பாய்வு', researchAnalysis: 'ஆராய்ச்சி பகுப்பாய்வு', askCopilot: 'வானிலை, எச்சரிக்கைகள் அல்லது பாதுகாப்பு பற்றி கேளுங்கள்…', syncing: 'MOSDAC ஒத்திசைக்கிறது...', sync: 'MOSDAC ஒத்திசை', archiveYear: 'காப்பக ஆண்டு:', cyclone: 'புயல்:', feedsActive: 'SCORPIO ஊட்டங்கள் செயலில்', status: 'நிலை:' },
  bn: { dashboard: 'ড্যাশবোর্ড', liveMonitoring: 'লাইভ পর্যবেক্ষণ', cycloneTracker: 'ঘূর্ণিঝড় ট্র্যাকার', rapidIntensification: 'দ্রুত তীব্রীকরণ', forecastModels: 'পূর্বাভাস ও মডেল', impactRiskMap: 'প্রভাব ও ঝুঁকি মানচিত্র', alertsNotifications: 'সতর্কতা ও বিজ্ঞপ্তি', historicalCyclones: 'ঐতিহাসিক ঘূর্ণিঝড়', analyticsReports: 'বিশ্লেষণ ও প্রতিবেদন', aiCopilot: 'AI সহকারী', accountDatabase: 'অ্যাকাউন্ট ও ডেটাবেস', settings: 'সেটিংস', feedback: 'মতামত', navigation: 'নেভিগেশন', new: 'নতুন', systemStatus: 'সিস্টেম অবস্থা', allSystemsOperational: 'সব সিস্টেম সচল', dataSourcesOnline: 'ডেটা উৎস অনলাইনে', viewDataSources: 'ডেটা উৎস দেখুন', search: 'ঘূর্ণিঝড়, স্থান, ID খুঁজুন...', clear: 'মুছুন', install: 'ইনস্টল করুন', installed: 'PWA ইনস্টল হয়েছে', language: 'ভাষা', preferredLanguage: 'পছন্দের প্রদর্শন ভাষা', savePreferences: 'পছন্দ সংরক্ষণ করুন', preferencesSaved: 'পছন্দ সংরক্ষিত হয়েছে!', languageHelp: 'CycloneAI ইন্টারফেস এবং AI সহকারীর ভাষা বেছে নিন।', units: 'আবহাওয়া একক', windUnit: 'বায়ুর গতির একক', pressureUnit: 'বায়ুমণ্ডলীয় চাপের একক', feedCache: 'MOSDAC ফিড ও ক্যাশ', syncFrequency: 'MOSDAC টেলিমেট্রি সিঙ্ক ব্যবধান', channel: 'ডিফল্ট স্যাটেলাইট চ্যানেল', dataCache: 'ডেটা অখণ্ডতা ও ক্যাশ রিসেট', clearCache: 'ব্রাউজার ক্যাশ মুছুন', chat: 'CycloneAI চ্যাট', conversationActive: 'কথোপকথন সক্রিয়', publicGuidance: 'জনসাধারণের নির্দেশনা', responseCoordination: 'প্রতিক্রিয়া সমন্বয়', coastalOperations: 'উপকূলীয় কার্যক্রম', forecastAnalysis: 'পূর্বাভাস বিশ্লেষণ', researchAnalysis: 'গবেষণা বিশ্লেষণ', askCopilot: 'আবহাওয়া, সতর্কতা বা নিরাপত্তা সম্পর্কে জিজ্ঞাসা করুন…', syncing: 'MOSDAC সিঙ্ক হচ্ছে...', sync: 'MOSDAC সিঙ্ক করুন', archiveYear: 'সংরক্ষণাগার বছর:', cyclone: 'ঘূর্ণিঝড়:', feedsActive: 'SCORPIO ফিড সক্রিয়', status: 'অবস্থা:' },
  or: { dashboard: 'ଡ୍ୟାସବୋର୍ଡ', liveMonitoring: 'ସିଧାସଳଖ ନିରୀକ୍ଷଣ', cycloneTracker: 'ବାତ୍ୟା ଟ୍ରାକର', rapidIntensification: 'ଦ୍ରୁତ ତୀବ୍ରତା', forecastModels: 'ପୂର୍ବାନୁମାନ ଓ ମଡେଲ', impactRiskMap: 'ପ୍ରଭାବ ଓ ବିପଦ ମାନଚିତ୍ର', alertsNotifications: 'ସତର୍କତା ଓ ବିଜ୍ଞପ୍ତି', historicalCyclones: 'ଐତିହାସିକ ବାତ୍ୟା', analyticsReports: 'ବିଶ୍ଳେଷଣ ଓ ରିପୋର୍ଟ', aiCopilot: 'AI ସହାୟକ', accountDatabase: 'ଖାତା ଓ ଡାଟାବେସ', settings: 'ସେଟିଂସ', feedback: 'ମତାମତ', navigation: 'ନାଭିଗେସନ', new: 'ନୂଆ', systemStatus: 'ସିଷ୍ଟମ ସ୍ଥିତି', allSystemsOperational: 'ସମସ୍ତ ସିଷ୍ଟମ କାର୍ଯ୍ୟକ୍ଷମ', dataSourcesOnline: 'ଡାଟା ଉତ୍ସ ଅନଲାଇନ୍', viewDataSources: 'ଡାଟା ଉତ୍ସ ଦେଖନ୍ତୁ', search: 'ବାତ୍ୟା, ସ୍ଥାନ, ID ଖୋଜନ୍ତୁ...', clear: 'ସଫା କରନ୍ତୁ', install: 'ଇନଷ୍ଟଲ କରନ୍ତୁ', installed: 'PWA ଇନଷ୍ଟଲ ହୋଇଛି', language: 'ଭାଷା', preferredLanguage: 'ପସନ୍ଦର ପ୍ରଦର୍ଶନ ଭାଷା', savePreferences: 'ପସନ୍ଦ ସଞ୍ଚୟ କରନ୍ତୁ', preferencesSaved: 'ପସନ୍ଦ ସଞ୍ଚୟ ହେଲା!', languageHelp: 'CycloneAI ଇଣ୍ଟରଫେସ ଓ AI ସହାୟକ ପାଇଁ ଭାଷା ବାଛନ୍ତୁ।', units: 'ପାଣିପାଗ ଏକକ', windUnit: 'ପବନ ବେଗ ଏକକ', pressureUnit: 'ବାୟୁମଣ୍ଡଳୀୟ ଚାପ ଏକକ', feedCache: 'MOSDAC ଫିଡ୍ ଓ କ୍ୟାଶ୍', syncFrequency: 'MOSDAC ଟେଲିମେଟ୍ରି ସିଙ୍କ ଅନ୍ତରାଳ', channel: 'ଡିଫଲ୍ଟ ସାଟେଲାଇଟ ଚ୍ୟାନେଲ', dataCache: 'ଡାଟା ଅଖଣ୍ଡତା ଓ କ୍ୟାଶ୍ ରିସେଟ୍', clearCache: 'ବ୍ରାଉଜର କ୍ୟାଶ୍ ସଫା କରନ୍ତୁ', chat: 'CycloneAI ଚାଟ୍', conversationActive: 'କଥାବାର୍ତ୍ତା ସକ୍ରିୟ', publicGuidance: 'ସାଧାରଣ ମାର୍ଗଦର୍ଶନ', responseCoordination: 'ପ୍ରତିକ୍ରିୟା ସମନ୍ୱୟ', coastalOperations: 'ଉପକୂଳ କାର୍ଯ୍ୟ', forecastAnalysis: 'ପୂର୍ବାନୁମାନ ବିଶ୍ଳେଷଣ', researchAnalysis: 'ଗବେଷଣା ବିଶ୍ଳେଷଣ', askCopilot: 'ପାଣିପାଗ, ସତର୍କତା କିମ୍ବା ସୁରକ୍ଷା ବିଷୟରେ ପଚାରନ୍ତୁ…', syncing: 'MOSDAC ସିଙ୍କ ହେଉଛି...', sync: 'MOSDAC ସିଙ୍କ କରନ୍ତୁ', archiveYear: 'ଆର୍କାଇଭ ବର୍ଷ:', cyclone: 'ବାତ୍ୟା:', feedsActive: 'SCORPIO ଫିଡ୍ ସକ୍ରିୟ', status: 'ସ୍ଥିତି:' },
  te: { dashboard: 'డాష్‌బోర్డ్', liveMonitoring: 'ప్రత్యక్ష పర్యవేక్షణ', cycloneTracker: 'తుఫాను ట్రాకర్', rapidIntensification: 'వేగవంతమైన తీవ్రత', forecastModels: 'అంచనా మరియు నమూనాలు', impactRiskMap: 'ప్రభావం మరియు ప్రమాద పటం', alertsNotifications: 'హెచ్చరికలు మరియు నోటిఫికేషన్లు', historicalCyclones: 'చారిత్రక తుఫానులు', analyticsReports: 'విశ్లేషణ మరియు నివేదికలు', aiCopilot: 'AI సహాయకుడు', accountDatabase: 'ఖాతా మరియు డేటాబేస్', settings: 'సెట్టింగ్‌లు', feedback: 'అభిప్రాయం', navigation: 'నావిగేషన్', new: 'కొత్తది', systemStatus: 'సిస్టమ్ స్థితి', allSystemsOperational: 'అన్ని వ్యవస్థలు పనిచేస్తున్నాయి', dataSourcesOnline: 'డేటా మూలాలు ఆన్‌లైన్‌లో ఉన్నాయి', viewDataSources: 'డేటా మూలాలను చూడండి', search: 'తుఫాను, స్థలం, ID కోసం వెతకండి...', clear: 'తొలగించు', install: 'ఇన్‌స్టాల్ చేయండి', installed: 'PWA ఇన్‌స్టాల్ చేయబడింది', language: 'భాష', preferredLanguage: 'ఇష్టమైన ప్రదర్శన భాష', savePreferences: 'ప్రాధాన్యతలను సేవ్ చేయండి', preferencesSaved: 'ప్రాధాన్యతలు సేవ్ అయ్యాయి!', languageHelp: 'CycloneAI ఇంటర్‌ఫేస్ మరియు AI సహాయకుడి కోసం భాషను ఎంచుకోండి.', units: 'వాతావరణ యూనిట్లు', windUnit: 'గాలి వేగ యూనిట్', pressureUnit: 'వాతావరణ పీడన యూనిట్', feedCache: 'MOSDAC ఫీడ్ మరియు క్యాష్', syncFrequency: 'MOSDAC టెలిమెట్రీ సింక్ విరామం', channel: 'డిఫాల్ట్ ఉపగ్రహ ఛానెల్', dataCache: 'డేటా సమగ్రత మరియు క్యాష్ రీసెట్', clearCache: 'బ్రౌజర్ క్యాష్‌ను తొలగించండి', chat: 'CycloneAI చాట్', conversationActive: 'సంభాషణ సక్రియంగా ఉంది', publicGuidance: 'ప్రజా మార్గదర్శకత్వం', responseCoordination: 'ప్రతిస్పందన సమన్వయం', coastalOperations: 'తీర కార్యకలాపాలు', forecastAnalysis: 'అంచనా విశ్లేషణ', researchAnalysis: 'పరిశోధన విశ్లేషణ', askCopilot: 'వాతావరణం, హెచ్చరికలు లేదా భద్రత గురించి అడగండి…', syncing: 'MOSDAC సింక్ అవుతోంది...', sync: 'MOSDAC సింక్ చేయండి', archiveYear: 'ఆర్కైవ్ సంవత్సరం:', cyclone: 'తుఫాను:', feedsActive: 'SCORPIO ఫీడ్‌లు సక్రియంగా ఉన్నాయి', status: 'స్థితి:' },
} as const;

type I18n = { language: LanguageCode; setLanguage: (language: LanguageCode) => void; t: (key: TranslationKey) => string };
const I18nContext = createContext<I18n | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = JSON.parse(localStorage.getItem('cycloneai_settings') || '{}').language;
    return SUPPORTED_LANGUAGES.some(({ code }) => code === saved) ? saved : 'en';
  });
  const setLanguage = (next: LanguageCode) => {
    const settings = JSON.parse(localStorage.getItem('cycloneai_settings') || '{}');
    localStorage.setItem('cycloneai_settings', JSON.stringify({ ...settings, language: next }));
    setLanguageState(next);
  };
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key: TranslationKey) => translations[language][key].replace(/CycloneAI/g, PRODUCT_NAME),
  }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const context = useContext(I18nContext);
  if (!context) throw new Error('useI18n must be used within LanguageProvider');
  return context;
}
